version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: RabbitMQ/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5100
    depends_on:
      - rabbitmq-server
    ports:
      - 5100:5100
  rabbitmq-server:
    image: "rabbitmq:management"
    container_name: rabbitmq-server
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.5